spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*" #允许跨域
            allowedMethods: #支持的方式
              - GET
              - Post
              - PUT
              - DELETE
      routes:
        #唯一标识符名称
          - id : changgou_gateway_routs
            #lb:loadBalancerClient：实现负载均衡，goods微服务的名字
            uri: lb://user
            predicates:
            #用户请求的域名规则配置，所有以cloud.itheima.com请求都将被路由http://localhost:18081微服务
            #- Host=cloud.itheima.com**
            #所有以/brand开始的请求，都路由到http://localhost:18081微服务
            # - Path=/api/brand/**
            - Path=/**

            filters:
            #在请求的路径中加上一个前缀，如http://localhost/goods，加上后：http://localhost/api/goods
            #- PrefixPath=/api
            #去掉一个前缀，例如：http://localhost/api/goods ,
            #加上这个参数后真实的请求http://localhost/goods
            - StripPrefix=1
            - name: RequestRateLimiter # 请求数限流，名字不能随便写
              args:
                #用户身份唯一识别标识符
                key-resolver: "#{@ipKeyResolver}"
                #每秒钟允许有一个请求
                redis-rate-limiter.replenishRate: 1
                #允许并发有4个请求[宽限的个数]
                redis-rate-limiter.burstCapacity: 4

server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://47.94.224.82:7001/eureka
  instance:
    prefer-ip-address: true
management:
        endpoint:
          gateway:
            enabled: true
          web:
            exposure:
              include: true