spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*" #允许跨域
            allowedMethods: #支持的方式
              - GET
              - Post
              - PUT
              - DELETE
      routes:
          - id : goods
            uri: lb://goods
            predicates:
              - Path=/goods/**
            #filters:
            #  - StripPrefix=1
            #  #- name: RequestRateLimiter # 请求数限流，名字不能随便写
            #    args:
            #    #用户身份唯一识别标识符
            #      key-resolver: "#{@ipKeyResolver}"
            #    #每秒钟允许有一个请求
            #      redis-rate-limiter.replemishRate: 1
            #    #允许并发有4个请求[宽限的个数]
            #      redis-rate-limiter.burstCapacity: 4

server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://47.94.224.82:7001/eureka
  instance:
    prefer-ip-address: true
management:
        endpoint:
          gateway:
            enabled: true
          web:
            exposure:
              include: true