server:
  port: 7001
eureka:
  instance:
    hostname: 47.94.224.82
  client:
    register-with-eureka: false   #是否将自己注册到eureka中
    fetch-registry: false         #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭保护机制，确保注册中心可以将不正确的实例剔除掉，默认为true