spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: file
server:
  port: 9008
eureka:
  client:
    service-url:
      defaultZone: http://47.94.224.82:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true