server:
  port: 9200
spring:
  application:
    name: user-auth
  redis:
    host: 47.94.224.82
    port: 6379
    password: 970425
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.94.224.82:3306/changgou_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    hikari:
      max-lifetime: 500000
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://47.94.224.82:7001/eureka
auth:
  ttl: 3600  #token存储到redis的过期时间
  clientId: changgou   #客户端ID
  clientSecret: changgou  #客户端密钥
  cookieDomain: localhost
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/changgou.jks  #本地证书路径
    secret: changgou                   #本地证书密钥
    alias: changgou                    #证书的别名
    password: changgou                 #证书密码